version: '3.8'

services:
  rpi-producer:
    build: . 
    image: rpi-data-producer:latest
    restart: always
    environment:
      KAFKA_BROKER: 192.168.1.30:9092
      KAFKA_TOPIC: site_sensors
    mem_limit: 256m
